---
# tasks file for debian
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Aptitude safe upgrade
  become: true
  ansible.builtin.apt:
    update_cache: false
    upgrade: safe

- name: Apt autoremove
  become: true
  ansible.builtin.apt:
    update_cache: false
    autoremove: true

- name: Install packages
  when: apt_packages is defined
  become: true
  ansible.builtin.apt:
    state: present
    pkg: "{{ apt_packages }}"
    update_cache: false

- name: Include Bash role
  ansible.builtin.include_role:
    name: dronenb.bash

# This must come after the apt cache update
- name: Include Vim role
  ansible.builtin.include_role:
    name: dronenb.vim
